CuraPersonaggio.CuraPersonaggio.costoSchieramento=1
CuraPersonaggio.CuraPersonaggio.cura=10
CuraPersonaggio.CuraPersonaggio.immagine=cura.jpg

BloccaAttacco.BloccaAttacco.costoSchieramento=1
BloccaAttacco.BloccaAttacco.immagine=congela.jpg

RendiInvulnerabile.RendiInvulnerabile.costoSchieramento=1
RendiInvulnerabile.RendiInvulnerabile.immagine=invulnerabile.jpg

Fulmine.Fulmine.costoSchieramento=3
Fulmine.Fulmine.danno=50
Fulmine.Fulmine.immagine=fulmine.jpg

Furia.Furia.costoSchieramento=3
Furia.Furia.aumento=10
Furia.Furia.immagine=furia.jpg