# Configurazione dei personaggi (per ogni categoria)
#FORMATO ClassaCategoria.NOME.attributo=valoreAttributo

#Tanks
##Gigante
###valori fittizi
Tank.GIGANTE.vita=100
Tank.GIGANTE.danno=30
Tank.GIGANTE.mossaSpeciale=ricaricaEnergia
Tank.GIGANTE.immagine=gigante.jpg