# FORMATO ClassaCategoria.NOME.attributo=valoreAttributo
# valori fittizi
# Il mana non è presente perché è impostato a 0 in automatico

Tank.GIGANTE.costoSchieramento=3
Tank.GIGANTE.vita=150
Tank.GIGANTE.armatura=30
Tank.GIGANTE.danno=25
Tank.GIGANTE.mossaSpeciale=ricaricaEnergia
Tank.GIGANTE.immagine=gigante.jpg

Tank.GOLEM.costoSchieramento=3
Tank.GOLEM.vita=200
Tank.GOLEM.armatura=10
Tank.GOLEM.danno=20
Tank.GOLEM.mossaSpeciale=ricaricaEnergia
Tank.GOLEM.immagine=golem.jpg

Tank.PEKKA.costoSchieramento=4
Tank.PEKKA.vita=150
Tank.PEKKA.armatura=15
Tank.PEKKA.danno=40
Tank.PEKKA.mossaSpeciale=attaccaDueVolte
Tank.PEKKA.immagine=pekka.jpg

Assassino.BOMBAROLO.costoSchieramento=2
Assassino.BOMBAROLO.vita=50
Assassino.BOMBAROLO.armatura=5
Assassino.BOMBAROLO.danno=50
Assassino.BOMBAROLO.mossaSpeciale=attaccaDiretto
Assassino.BOMBAROLO.immagine=bombarolo.jpg

Assassino.FANTASMA.costoSchieramento=3
Assassino.FANTASMA.vita=80
Assassino.FANTASMA.armatura=40
Assassino.FANTASMA.danno=35
Assassino.FANTASMA.mossaSpeciale=attaccaDiretto
Assassino.FANTASMA.immagine=fantasma.png

Assassino.MINIPEKKA.costoSchieramento=2
Assassino.MINIPEKKA.vita=75
Assassino.MINIPEKKA.armatura=15
Assassino.MINIPEKKA.danno=30
Assassino.MINIPEKKA.mossaSpeciale=attaccaDueVolte
Assassino.MINIPEKKA.immagine=minipekka.jpg

Mago.CURATRICE.costoSchieramento=4
Mago.CURATRICE.vita=65
Mago.CURATRICE.armatura=25
Mago.CURATRICE.danno=5
Mago.CURATRICE.mossaSpeciale=ricaricaEnergiaStrada
Mago.CURATRICE.immagine=curatrice.jpg

Mago.STREGONEGHIACCIO.costoSchieramento=3
Mago.STREGONEGHIACCIO.vita=80
Mago.STREGONEGHIACCIO.armatura=15
Mago.STREGONEGHIACCIO.danno=15
Mago.STREGONEGHIACCIO.mossaSpeciale=doppioArmor
Mago.STREGONEGHIACCIO.immagine=ghiaccio.png

Mago.STREGONEFUOCO.costoSchieramento=3
Mago.STREGONEFUOCO.vita=50
Mago.STREGONEFUOCO.armatura=15
Mago.STREGONEFUOCO.danno=40
Mago.STREGONEFUOCO.mossaSpeciale=attaccaDueVolte
Mago.STREGONEFUOCO.immagine=fuoco.jpg