# Configurazione dei personaggi (per ogni categoria)
#FORMATO ClassaCategoria.NOME.attributo=valoreAttributo

#Il mano non è presente perché è impostato a 0 in automatico
#Tanks
##Gigante
###valori fittizi
Tank.GIGANTE.costoSchieramento=2
Tank.GIGANTE.vita=100
Tank.GIGANTE.armatura=20
Tank.GIGANTE.danno=30
Tank.GIGANTE.mossaSpeciale=ricaricaEnergia
Tank.GIGANTE.immagine=gigante.jpg

Tank.GOLEM.costoSchieramento=3
Tank.GOLEM.vita=200
Tank.GOLEM.armatura=10
Tank.GOLEM.danno=15
Tank.GOLEM.mossaSpeciale=ricaricaEnergia
Tank.GOLEM.immagine=golem.jpg